### PR TITLE
Add libssl-dev as a build-export dependency

### PR DESCRIPTION
**Pull request by ardabbour**

### CODE REVIEW

**Comment by StefanFabian** [comment]
Thank you for your contribution.
I have looked at it and unless I missed something it doesn't seem necessary to make `libssl-dev` a build-export dependency since it is only used/included in `.cpp` files, not in any headers.
Could you elaborate on why you think it is missing?

**Comment by ardabbour** [comment]
I have a library that depends on `ros_babel_fish` which blew up in build over `industrial_ci` because it attempted to link with `libssl.so` (even though I am not using it in anyway directly) but failed to find it. This happened only with the noetic version, it passed normally with the melodic version.

When I added `<depend>libssl-dev</depend>` to my package that depends on `ros_babel_fish`, and that solved the problem. If we take a look at the file lists of `openssl` and `libssl-dev` we can see that it is `libssl-dev` that contains the relevant libraries and headers (including `libssl.so`)

**Comment by StefanFabian** [comment]
Sorry for the late reply.
I have looked up the contents of the debian packages and confirmed that it is actually lilbssl-dev or libssl1.1 which contains the library though libssl-dev also contains a symbolic link to libssl1.1.so from libssl1.1.

Thank you for your contribution!

**Comment by ardabbour** [comment]
Would it be possible to release these changes? :)

**Comment by StefanFabian** [comment]
Sure, no problem. Submitted a new release.

**Pull request merged**
